import { Link } from 'react-router-dom'
import '../styles/Legal.css'

export default function PrivacyPolicy() {
  return (
    <div className="legal-page">
      <div className="legal-body">
        <Link to="/register" className="legal-back">← Back to sign up</Link>

        <h1>Privacy Policy</h1>
        <p className="legal-updated">Last updated: {new Date().getFullYear()}</p>

        <p>
          This policy explains what information Flowboard collects when you create an
          account and use the app, and how it's used. Flowboard is a project-management
          tool built for organizing boards, tasks, and team collaboration.
        </p>

        <h2>Information we collect</h2>
        <ul>
          <li><strong>Account details</strong> — your full name, username, email address, and a securely hashed password (we never store your password in plain text).</li>
          <li><strong>Project content</strong> — the projects, lists, cards, descriptions, assignees, and comments you and your teammates create.</li>
          <li><strong>Usage activity</strong> — notifications generated by actions you and your collaborators take on shared projects (e.g. a card being moved or commented on).</li>
        </ul>

        <h2>How we use it</h2>
        <ul>
          <li>To create and secure your account, and let you sign in.</li>
          <li>To operate the core features you use — boards, real-time updates, notifications, and exports.</li>
          <li>To send you a one-time welcome email when you sign up. We don't send marketing email.</li>
          <li>Your name, username, and activity are visible to other members of projects you share with them — that's how collaboration works.</li>
        </ul>

        <h2>Data storage</h2>
        <p>
          Your data is stored in the application's database for as long as your account
          exists. Deleting a project permanently removes its lists, cards, and comments.
        </p>

        <h2>Your choices</h2>
        <p>
          You can rename or delete projects you own, delete individual cards, and sign
          out at any time. If you'd like your account and data removed entirely, contact
          whoever administers your Flowboard instance.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about this policy can be directed to your Flowboard administrator.
        </p>
      </div>
    </div>
  )
}
